$(document).ready(function(){
    $('.logo_slider').owlCarousel({
        loop:false,
        margin:20,
        autoplay:false,
        autoplayTimeout:3000,
        nav:false,
        dots:true,
        responsive:{
            0:{
                items:3
            },
            600:{
                items:4
            },
            1000:{
                items:5
            }
        }
    })
    $('.color_slider').owlCarousel({
        loop:false,
        margin:20,
        autoplay:false,
        autoplayTimeout:3000,
        nav:false,
        dots:true,
        responsive:{
            0:{
                margin:10,
                autoplay:false,
                items:1
            },
            600:{
				margin:10,
                items:2
            },
            1000:{
                items:3
            }
        }
    })

    $('.price3').owlCarousel({
        loop:false,
        margin:20,
        autoplay:false,
        autoplayTimeout:3000,
        nav:false,
        dots:true,
        responsive:{
            0:{
                margin:10,
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3
            }
        }
    })
	
    $('.price4').owlCarousel({
        loop:false,
        margin:20,
        autoplay:false,
        autoplayTimeout:3000,
        nav:false,
        dots:true,
        responsive:{
            0:{
                margin:10,
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    })

    $('.cat_slider').owlCarousel({
        loop:false,
        margin:10,
        autoplay:false,
        autoplayTimeout:3000,
        nav:false,
        dots:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:1
            }
        }
    })

    $('.stories').owlCarousel({
        loop:false,
        margin:20,
        autoplay:false,
        autoplayTimeout:3000,
        nav:false,
        dots:true,
        responsive:{
            0:{
                margin:10,
                items:2
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    })
	
    $('.testi_slider').owlCarousel({
        loop:true,
        margin:20,
        autoplay:true,
        autoplayTimeout:2600,
        nav:false,
        dots:true,
        responsive:{
            0:{
                margin:10,
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:4
            }
        }
    })

	$('.services_slider').owlCarousel({
        loop:false,
        margin:20,
        autoplay:false,
        autoplayTimeout:3000,
        nav:true,
        dots:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:1
            }
        }
    })

});